---
- name: Deploy Chuck Jokes App
  hosts: localhost
  become: yes
  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Pull Docker image
      docker_image:
        name: chuck-image
        source: pull

    - name: Run Docker container
      docker_container:
        name: chuck-app
        image: chuck-image
        state: started
        restart_policy: always
        ports:
          - "5000:5000"
