- name: Deploy Chuck Norris Jokes App
  hosts: your_servers
  become: yes

  tasks:
    - name: Update package cache
      apk:
        update_cache: yes
      become: yes

    - name: Install Docker
      apk:
        name: docker
        state: present
      become: yes

    - name: Pull Docker image
      docker_image:
        name: chuck-image
        source: pull
      become: yes

    - name: Run Docker container
      docker_container:
        name: chuck-norris-app
        image: chuck-image
        state: started
        restart_policy: always
        ports:
          - "5000:5000"
      become: yes
